### ISSUE TITLE
KeyPad Not shown in first page

### ISSUE THREAD

**Issue by shayegh** [TylerStanish/react-native-phone-auth-component#3]
Hi,
Thanks for your Component.
I have an issue when I use your component in android the keypad is not shown in first page. and after I click the county picker and select country and return to first page the Verification button text is removed. please help me.
![screenshot_1531838810](https://user-images.githubusercontent.com/10929932/42824879-064448ee-89f6-11e8-8052-dced9521739b.png)

**Comment by TylerStanish** [comment]
Hmm, I'll try to reproduce it

**Comment by TylerStanish** [comment]
Oh yes I see what you mean. Do you know if this only isn't working on an emulator or if it is also a problem on a physical phone? I don't have an android but on iOS it's fine

**Comment by shayegh** [comment]
Hi,
both of it . on emulator and real phone. in real phone (Galaxy j7 prime) some times keypad not shown
i think there is some problem with key pad

**Comment by TylerStanish** [comment]
A short update for anybody who may be seeing this... 

the problem is that on Android calling the focus() method on a ```TextInput``` ref does not always focus on the ```TextInput``` and show the keyboard. But for some odd reason this is only a problem on Android. I'm definitely open to accepting pull requests and I have been trying to solve this problem for a couple of days but not getting much luck so far...

Thank you shayegh for exposing this really bad bug

**Comment by TylerStanish** [comment]
Alright! As of version 0.1.3 this issue is resolved, all i did was simply change

```javascript
this.setState({countryInfo: e}, () => {
  this._ref.focus();
});
```

to

```javascript
this._ref.focus();
this.setState({countryInfo: e});
```
in the index.js where the country-picker callback is located for selecting a country

**Comment by shayegh** [comment]
How to upgrade my code?
I use npm update 
but the problem still exist

**Comment by TylerStanish** [comment]
In your package.json how is your semantic versioning for the dependency? Is it prefixed with ```^``` or ```~```? Another way to update dependencies is to ```npm install``` like normal but add a ```@latest``` to the end like so:
```npm i --save react-native-phone-auth-component@latest```
and if none of these work you I suppose you could just uninstall it and install it again
